# Setup
title:        Clarion CSS Architecture and CLI Documentation
tagline:      A CSS architecting framework for building modular and easy-to-maintain websites.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Burton Smith
  url:        https://breakstuff.io 

# Gems
gems:
  - jekyll-paginate
  - jekyll-sitemap

#Others
markdown: kramdown

sass:
    sass_dir: src/sass

exclude: [src, webpack.config.js, jekyll-cayman-theme.gemspec, package.json, package-lock.json, postcss.config.js, README.md, Gemfile, Gemfile.lock, node_modules]