# Setup
title:        Clarion CLI Documentation
tagline:      A framework for building modular and easy-to-maintain websites.
baseurl:      "/clarion"
paginate:     1

# About/contact
author:
  name:       Burton Smith
  url:        https://breakstuff.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

sass:
    sass_dir: src/sass

exclude: [src, webpack.config.js, jekyll-cayman-theme.gemspec, package.json, postcss.config.js, README.md, Gemfile, Gemfile.lock]